FROM node:22-alpine

WORKDIR /app

# Instalar dependencias primero para cachear esta capa
COPY package*.json ./
RUN npm install --legacy-peer-deps

COPY . .

# Exponer el puerto
EXPOSE 3000

# Añadir el flag '--legacy-watch' si nodemon en Docker tiene problemas de sincronizacion en Windows
CMD ["npm", "run", "dev"]
