const fs = require('fs');
const path = require('path');

const requiredKeysMap = {
    'FIREBASE_API_KEY': ['FIREBASE_API_KEY', 'API_KEY', 'apiKey'],
    'FIREBASE_AUTH_DOMAIN': ['FIREBASE_AUTH_DOMAIN', 'AUTH_DOMAIN', 'authDomain'],
    'FIREBASE_PROJECT_ID': ['FIREBASE_PROJECT_ID', 'PROJECT_ID', 'projectId'],
    'FIREBASE_STORAGE_BUCKET': ['FIREBASE_STORAGE_BUCKET', 'STORAGE_BUCKET', 'storageBucket'],
    'FIREBASE_MESSAGING_SENDER_ID': ['FIREBASE_MESSAGING_SENDER_ID', 'MESSAGING_SENDER_ID', 'messagingSenderId'],
    'FIREBASE_APP_ID': ['FIREBASE_APP_ID', 'APP_ID', 'appId'],
};

const missing = [];
const configArgs = {};

for (const [key, searchKeys] of Object.entries(requiredKeysMap)) {
    const foundKey = searchKeys.find(k => process.env[k]);
    if (foundKey) {
        configArgs[key] = process.env[foundKey];
    } else {
        missing.push(key);
    }
}

if (missing.length) {
    console.error('  Missing required environment variables:', missing.join(', '));
    console.error('   Set them in the Vercel project dashboard → Settings → Environment Variables.');
    process.exit(1);
}

const content = `//   AUTO-GENERATED by scripts/generate-env.js — do not edit manually
export const environment = {
    production: true,
    apiUrl: '${process.env.API_URL || 'https://kanbanboard-yckr.onrender.com/api'}',
    socketUrl: '${process.env.SOCKET_URL || 'https://kanbanboard-yckr.onrender.com'}',
    firebase: {
        apiKey: '${configArgs.FIREBASE_API_KEY}',
        authDomain: '${configArgs.FIREBASE_AUTH_DOMAIN}',
        projectId: '${configArgs.FIREBASE_PROJECT_ID}',
        storageBucket: '${configArgs.FIREBASE_STORAGE_BUCKET}',
        messagingSenderId: '${configArgs.FIREBASE_MESSAGING_SENDER_ID}',
        appId: '${configArgs.FIREBASE_APP_ID}',
        measurementId: '${process.env.FIREBASE_MEASUREMENT_ID || process.env.MEASUREMENT_ID || process.env.measurementId || ''}'
    }
};
`;

const outPath = path.join(__dirname, '..', 'src', 'environments', 'environment.prod.ts');
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, content);
console.log('✅  environment.prod.ts generated successfully.');
