const fs = require('fs');
const path = require('path');

let envPath = path.join(__dirname, '..', '.env');
if (!fs.existsSync(envPath)) {
    envPath = path.join(__dirname, '..', '..', 'backend', '.env');
}

if (fs.existsSync(envPath)) {
    const envContent = fs.readFileSync(envPath, 'utf8');
    envContent.split('\n').forEach(line => {
        const match = line.match(/^\s*([\w.-]+)\s*=\s*(.*)?\s*$/);
        if (match) {
            const key = match[1];
            let value = match[2] || '';
            value = value.replace(/^['"](.*)['"]$/, '$1').trim();
            if (!process.env[key]) process.env[key] = value;
        }
    });
}

const requiredKeysMap = {
    'FIREBASE_API_KEY': ['FIREBASE_API_KEY', 'API_KEY', 'apiKey'],
    'FIREBASE_AUTH_DOMAIN': ['FIREBASE_AUTH_DOMAIN', 'AUTH_DOMAIN', 'authDomain'],
    'FIREBASE_PROJECT_ID': ['FIREBASE_PROJECT_ID', 'PROJECT_ID', 'projectId'],
    'FIREBASE_STORAGE_BUCKET': ['FIREBASE_STORAGE_BUCKET', 'STORAGE_BUCKET', 'storageBucket'],
    'FIREBASE_MESSAGING_SENDER_ID': ['FIREBASE_MESSAGING_SENDER_ID', 'MESSAGING_SENDER_ID', 'messagingSenderId'],
    'FIREBASE_APP_ID': ['FIREBASE_APP_ID', 'APP_ID', 'appId'],
};

const missing = [];
const configArgs = {};

for (const [key, searchKeys] of Object.entries(requiredKeysMap)) {
    const foundKey = searchKeys.find(k => process.env[k]);
    if (foundKey) {
        configArgs[key] = process.env[foundKey];
    } else {
        missing.push(key);
    }
}

if (missing.length) {
    console.warn('Warning: Missing some Firebase environment variables: ' + missing.join(', '));
    console.warn('The app might not connect to Firebase correctly until these are provided at runtime or via environment.');
}

function cleanVar(val) {
    if (!val) return '';
    return val.replace(/^['"]+/, '').replace(/['"],?$/, '').replace(/['"]$/, '');
}

const content = `//   AUTO-GENERATED by scripts/generate-env.js — do not edit manually
export const environment = {
    production: true,
    apiUrl: '${cleanVar(process.env.API_URL) || 'https://kanbanboard-yckr.onrender.com/api'}',
    socketUrl: '${cleanVar(process.env.SOCKET_URL) || 'https://kanbanboard-yckr.onrender.com'}',
    firebase: {
        apiKey: '${cleanVar(configArgs.FIREBASE_API_KEY)}',
        authDomain: '${cleanVar(configArgs.FIREBASE_AUTH_DOMAIN)}',
        projectId: '${cleanVar(configArgs.FIREBASE_PROJECT_ID)}',
        storageBucket: '${cleanVar(configArgs.FIREBASE_STORAGE_BUCKET)}',
        messagingSenderId: '${cleanVar(configArgs.FIREBASE_MESSAGING_SENDER_ID)}',
        appId: '${cleanVar(configArgs.FIREBASE_APP_ID)}',
        measurementId: '${cleanVar(process.env.FIREBASE_MEASUREMENT_ID || process.env.MEASUREMENT_ID || process.env.measurementId)}'
    }
};
`;

const outPath = path.join(__dirname, '..', 'src', 'environments', 'environment.prod.ts');
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, content);
console.log('environment.prod.ts generated successfully.');
