#!/usr/bin/env node
// scripts/generate-env.js
// Generates src/environments/environment.prod.ts from environment variables.
// Run automatically by the "prebuild" npm script on Vercel.

const fs = require('fs');
const path = require('path');

const required = [
    'FIREBASE_API_KEY',
    'FIREBASE_AUTH_DOMAIN',
    'FIREBASE_PROJECT_ID',
    'FIREBASE_STORAGE_BUCKET',
    'FIREBASE_MESSAGING_SENDER_ID',
    'FIREBASE_APP_ID',
];

const missing = required.filter(k => !process.env[k]);
if (missing.length) {
    console.error('  Missing required environment variables:', missing.join(', '));
    console.error('   Set them in the Vercel project dashboard → Settings → Environment Variables.');
    process.exit(1);
}

const content = `//   AUTO-GENERATED by scripts/generate-env.js — do not edit manually
export const environment = {
    production: true,
    apiUrl: '${process.env.API_URL || 'https://kanbanboard-backend.vercel.app/api'}',
    socketUrl: '${process.env.SOCKET_URL || 'https://kanbanboard-backend.vercel.app'}',
    firebase: {
        apiKey: '${process.env.FIREBASE_API_KEY}',
        authDomain: '${process.env.FIREBASE_AUTH_DOMAIN}',
        projectId: '${process.env.FIREBASE_PROJECT_ID}',
        storageBucket: '${process.env.FIREBASE_STORAGE_BUCKET}',
        messagingSenderId: '${process.env.FIREBASE_MESSAGING_SENDER_ID}',
        appId: '${process.env.FIREBASE_APP_ID}',
        measurementId: '${process.env.FIREBASE_MEASUREMENT_ID || ''}'
    }
};
`;

const outPath = path.join(__dirname, '..', 'src', 'environments', 'environment.prod.ts');
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, content);
console.log('✅  environment.prod.ts generated successfully.');
