//   AUTO-GENERATED by scripts/generate-env.js — do not edit manually
export const environment = {
    production: true,
    apiUrl: 'https://kanbanboard-yckr.onrender.com/api',
    socketUrl: 'https://kanbanboard-yckr.onrender.com',
    firebase: {
        apiKey: '',
        authDomain: '',
        projectId: '',
        storageBucket: '',
        messagingSenderId: '',
        appId: '',
        measurementId: ''
    }
};
